---
output:
  sort-results: true
issues:
  max-issues-per-linter: 0 # infinite
  max-same-issues: 0 # infinite
run:
  modules-download-mode: vendor
linters-settings:
  #  errcheck:
  #    check-type-assertions: true
  staticcheck:
    checks: ["all", "-SA5008"]
  maligned:
    suggest-new: true
  misspell:
    ignore-words:
      - eles
      - alledges
  gocritic:
    # checks described here: https://go-critic.github.io/overview
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - commentFormatting
      - unnamedResult
linters:
  enable:
    - misspell
    - unconvert
    - gofmt
    - unparam
#    - nolintlint # RE-ENABLE AFTER THEY FIX GO1.18 STUFF
#    - maligned
#    - gocritic
#    - scopelint
#    - bodyclose
#    - sqlclosecheck
#    - prealloc
